#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef IDFLOW_SWIFT_H
#define IDFLOW_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IDFlow",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class App;
@class Document;
@class Face;
@class Video;
SWIFT_CLASS("_TtC6IDFlow16IDFlowAppearance")
@interface IDFlowAppearance : NSObject
@property (nonatomic, strong) App * _Nonnull app;
@property (nonatomic, strong) Document * _Nonnull document;
@property (nonatomic, strong) Face * _Nonnull face;
@property (nonatomic, strong) Video * _Nonnull video;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
SWIFT_CLASS("_TtCC6IDFlow16IDFlowAppearance3App")
@interface App : NSObject
@property (nonatomic, strong) UIColor * _Nonnull backgroundNavigationBar;
@property (nonatomic, strong) UIColor * _Nonnull foregroundNavigationBar;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCC6IDFlow16IDFlowAppearance8Document")
@interface Document : NSObject
@property (nonatomic, strong) UIColor * _Nullable primary;
@property (nonatomic, strong) UIColor * _Nullable onPrimary;
@property (nonatomic, strong) UIColor * _Nullable outline;
@property (nonatomic, strong) UIColor * _Nullable divider;
@property (nonatomic, strong) UIColor * _Nullable backgroundInstruction;
@property (nonatomic, strong) UIColor * _Nullable foregroundInstruction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
SWIFT_CLASS("_TtCC6IDFlow16IDFlowAppearance4Face")
@interface Face : NSObject
@property (nonatomic, strong) UIColor * _Nullable success;
@property (nonatomic, strong) UIColor * _Nullable error;
@property (nonatomic, strong) UIColor * _Nullable textMessage;
@property (nonatomic, strong) UIColor * _Nullable textCountdown;
@property (nonatomic, strong) UIColor * _Nullable loading;
@property (nonatomic, strong) UIColor * _Nullable backgroundInfo;
@property (nonatomic, strong) UIColor * _Nullable foregroundInfo;
@property (nonatomic, strong) UIColor * _Nullable strokeInfo;
@property (nonatomic, strong) UIImage * _Nullable infoImage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCC6IDFlow16IDFlowAppearance5Video")
@interface Video : NSObject
@property (nonatomic, strong) UIColor * _Nullable success;
@property (nonatomic, strong) UIColor * _Nullable error;
@property (nonatomic, strong) UIColor * _Nullable loading;
@property (nonatomic, strong) UIColor * _Nullable progressIndicator;
@property (nonatomic, strong) UIColor * _Nullable progressTrack;
@property (nonatomic, strong) UIColor * _Nullable stepDetectFocusedBackground;
@property (nonatomic, strong) UIColor * _Nullable stepDetectFocusedForeground;
@property (nonatomic, strong) UIColor * _Nullable stepFinishedBackground;
@property (nonatomic, strong) UIColor * _Nullable stepFinishedForeground;
@property (nonatomic, strong) UIColor * _Nullable stepMovingFocusedBackground;
@property (nonatomic, strong) UIColor * _Nullable stepMovingFocusedForeground;
@property (nonatomic, strong) UIColor * _Nullable stepMovingUnfocusedBackground;
@property (nonatomic, strong) UIColor * _Nullable stepMovingUnfocusedForeground;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IDFlowCameraSelector, open) {
  IDFlowCameraSelectorFront = 0,
  IDFlowCameraSelectorBack = 1,
};

@class IDFlowConfig;
@protocol IDFlowClientDelegate;
@class UINavigationController;
SWIFT_CLASS("_TtC6IDFlow12IDFlowClient")
@interface IDFlowClient : NSObject
+ (void)showScannerWithConfig:(IDFlowConfig * _Nonnull)config withDelegate:(id <IDFlowClientDelegate> _Nonnull)delegate;
+ (UINavigationController * _Nonnull)buildUINavigationControllerWithConfig:(IDFlowConfig * _Nonnull)config withDelegate:(id <IDFlowClientDelegate> _Nonnull)delegate showCancelButton:(BOOL)showCancelButton shouldDismiss:(BOOL)shouldDismiss SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class IDFlowResult;
@class IDFlowException;
SWIFT_PROTOCOL("_TtP6IDFlow20IDFlowClientDelegate_")
@protocol IDFlowClientDelegate
- (void)onCompletedWithResult:(IDFlowResult * _Nonnull)result;
- (void)onFailedWithException:(IDFlowException * _Nonnull)exception;
- (void)onCanceled;
@end

enum IDFlowLocale : NSInteger;
enum IDFlowEntryMode : NSInteger;
enum IDFlowPresentationStyle : NSInteger;
enum IDFlowTransformation : NSInteger;
@class IDFlowPreviewConfig;
@class IDFlowDocumentConfig;
@class IDFlowFaceConfig;
@class IDFlowVideoConfig;
SWIFT_CLASS("_TtC6IDFlow12IDFlowConfig")
@interface IDFlowConfig : NSObject
@property (nonatomic) enum IDFlowLocale locale;
@property (nonatomic) enum IDFlowEntryMode entryMode;
@property (nonatomic) enum IDFlowCameraSelector cameraSelector;
@property (nonatomic) enum IDFlowPresentationStyle presentationStyle;
@property (nonatomic) enum IDFlowTransformation transformation;
@property (nonatomic, strong) IDFlowPreviewConfig * _Nonnull previewConfig;
@property (nonatomic, strong) IDFlowDocumentConfig * _Nonnull documentConfig;
@property (nonatomic, strong) IDFlowFaceConfig * _Nonnull faceConfig;
@property (nonatomic, strong) IDFlowVideoConfig * _Nonnull videoConfig;
@property (nonatomic, strong) IDFlowAppearance * _Nonnull appearance;
- (nonnull instancetype)initWithLocale:(enum IDFlowLocale)locale entryMode:(enum IDFlowEntryMode)entryMode cameraSelector:(enum IDFlowCameraSelector)cameraSelector presentationStyle:(enum IDFlowPresentationStyle)presentationStyle transformation:(enum IDFlowTransformation)transformation previewConfig:(IDFlowPreviewConfig * _Nonnull)previewConfig documentConfig:(IDFlowDocumentConfig * _Nonnull)documentConfig faceConfig:(IDFlowFaceConfig * _Nonnull)faceConfig videoConfig:(IDFlowVideoConfig * _Nonnull)videoConfig appearance:(IDFlowAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum IDFlowDocumentUiVariant : NSInteger;
SWIFT_CLASS("_TtC6IDFlow20IDFlowDocumentConfig")
@interface IDFlowDocumentConfig : NSObject
@property (nonatomic) enum IDFlowDocumentUiVariant uiVariant;
@property (nonatomic) BOOL isResident;
@property (nonatomic) BOOL documentEditEnabled;
@property (nonatomic) BOOL detectDocumentDuringSelfie;
@property (nonatomic) BOOL countdownEnabled;
@property (nonatomic) BOOL flashlightEnabled;
@property (nonatomic) BOOL instructionEnabled;
- (nonnull instancetype)initWithUiVariant:(enum IDFlowDocumentUiVariant)uiVariant isResident:(BOOL)isResident documentEditEnabled:(BOOL)documentEditEnabled detectDocumentDuringSelfie:(BOOL)detectDocumentDuringSelfie countdownEnabled:(BOOL)countdownEnabled flashlightEnabled:(BOOL)flashlightEnabled instructionEnabled:(BOOL)instructionEnabled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
SWIFT_CLASS("_TtC6IDFlow20IDFlowDocumentResult")
@interface IDFlowDocumentResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull pinfl;
@property (nonatomic, readonly, copy) NSString * _Nonnull document;
@property (nonatomic, readonly, copy) NSString * _Nonnull lastName;
@property (nonatomic, readonly, copy) NSString * _Nonnull firstName;
@property (nonatomic, readonly, copy) NSString * _Nonnull birthDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull expiryDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull countryCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull mrz;
- (nonnull instancetype)initWithPinfl:(NSString * _Nullable)pinfl document:(NSString * _Nullable)document lastName:(NSString * _Nullable)lastName firstName:(NSString * _Nullable)firstName birthDate:(NSString * _Nullable)birthDate expiryDate:(NSString * _Nullable)expiryDate countryCode:(NSString * _Nullable)countryCode mrz:(NSString * _Nullable)mrz OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, IDFlowDocumentUiVariant, open) {
  IDFlowDocumentUiVariantVariant1 = 0,
  IDFlowDocumentUiVariantVariant2 = 1,
};

typedef SWIFT_ENUM(NSInteger, IDFlowEntryMode, open) {
  IDFlowEntryModeFullIdent = 0,
  IDFlowEntryModeSelfieThenDocument = 1,
  IDFlowEntryModeSelfieWithDocument = 2,
  IDFlowEntryModeDocumentOnly = 3,
  IDFlowEntryModeSelfieOnly = 4,
};

SWIFT_CLASS("_TtC6IDFlow15IDFlowException")
@interface IDFlowException : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly) NSInteger code;
- (nonnull instancetype)initWithMessage:(NSString * _Nonnull)message code:(NSInteger)code OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6IDFlow16IDFlowFaceConfig")
@interface IDFlowFaceConfig : NSObject
@property (nonatomic) CGFloat targetDistanceRatio;
@property (nonatomic) CGFloat faceCropPaddingRatio;
@property (nonatomic) BOOL useVideoIdentification;
@property (nonatomic) BOOL progressIndicatorEnabled;
@property (nonatomic) BOOL reasonMessageEnabled;
@property (nonatomic) BOOL countdownEnabled;
@property (nonatomic, copy) NSString * _Nonnull infoboxText;
- (nonnull instancetype)initWithTargetDistanceRatio:(CGFloat)targetDistanceRatio faceCropPaddingRatio:(CGFloat)faceCropPaddingRatio useVideoIdentification:(BOOL)useVideoIdentification progressIndicatorEnabled:(BOOL)progressIndicatorEnabled reasonMessageEnabled:(BOOL)reasonMessageEnabled countdownEnabled:(BOOL)countdownEnabled infoboxText:(NSString * _Nonnull)infoboxText OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6IDFlow17IDFlowFieldResult")
@interface IDFlowFieldResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull front;
@property (nonatomic, readonly, copy) NSString * _Nonnull back;
@property (nonatomic, readonly) double match;
- (nonnull instancetype)initWithFront:(NSString * _Nonnull)front back:(NSString * _Nonnull)back match:(double)match OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, IDFlowLocale, open) {
  IDFlowLocaleKyrgyz = 0,
  IDFlowLocaleEnglish = 1,
  IDFlowLocaleRussian = 2,
  IDFlowLocaleChinese = 3,
  IDFlowLocaleRomanian = 4,
};

typedef SWIFT_ENUM(NSInteger, IDFlowPresentationStyle, open) {
  IDFlowPresentationStyleFull = 0,
  IDFlowPresentationStyleSheet = 1,
};

SWIFT_CLASS("_TtC6IDFlow19IDFlowPreviewConfig")
@interface IDFlowPreviewConfig : NSObject
@property (nonatomic) BOOL showDocumentFrontPreview;
@property (nonatomic) BOOL showDocumentBackPreview;
@property (nonatomic) BOOL showSelfieWithDocumentPreview;
- (nonnull instancetype)initWithShowDocumentFrontPreview:(BOOL)showDocumentFrontPreview showDocumentBackPreview:(BOOL)showDocumentBackPreview showSelfieWithDocumentPreview:(BOOL)showSelfieWithDocumentPreview OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
SWIFT_CLASS("_TtC6IDFlow12IDFlowResult")
@interface IDFlowResult : NSObject
@property (nonatomic, readonly, strong) IDFlowDocumentResult * _Nonnull documentResult;
@property (nonatomic, readonly, strong) IDFlowDocumentResult * _Nonnull editableDocumentResult;
@property (nonatomic, readonly, copy) NSString * _Nonnull personalNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull idSeriesNumber;
@property (nonatomic, readonly, strong) IDFlowFieldResult * _Nonnull tin;
@property (nonatomic, readonly, strong) IDFlowFieldResult * _Nonnull passport;
@property (nonatomic, readonly, strong) UIImage * _Nullable selfie;
@property (nonatomic, readonly, strong) UIImage * _Nullable selfieWithDocument;
@property (nonatomic, readonly, strong) UIImage * _Nullable documentFace;
@property (nonatomic, readonly, strong) UIImage * _Nullable documentFront;
@property (nonatomic, readonly, strong) UIImage * _Nullable documentBack;
@property (nonatomic, readonly, copy) NSString * _Nullable faceData;
@property (nonatomic, readonly, copy) NSURL * _Nullable videoURL;
@property (nonatomic, readonly) BOOL isFaceOccluded;
- (nonnull instancetype)initWithDocumentResult:(IDFlowDocumentResult * _Nullable)documentResult editableDocumentResult:(IDFlowDocumentResult * _Nullable)editableDocumentResult personalNumber:(NSString * _Nonnull)personalNumber idSeriesNumber:(NSString * _Nonnull)idSeriesNumber tin:(IDFlowFieldResult * _Nonnull)tin passport:(IDFlowFieldResult * _Nonnull)passport selfie:(UIImage * _Nullable)selfie selfieWithDocument:(UIImage * _Nullable)selfieWithDocument documentFace:(UIImage * _Nullable)documentFace documentFront:(UIImage * _Nullable)documentFront documentBack:(UIImage * _Nullable)documentBack faceData:(NSString * _Nullable)faceData videoURL:(NSURL * _Nullable)videoURL isFaceOccluded:(BOOL)isFaceOccluded OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, IDFlowTransformation, open) {
  IDFlowTransformationAesGcm = 0,
  IDFlowTransformationAesCbc = 1,
};

enum IDFlowVideoUiVariant : NSInteger;
SWIFT_CLASS("_TtC6IDFlow17IDFlowVideoConfig")
@interface IDFlowVideoConfig : NSObject
@property (nonatomic) enum IDFlowVideoUiVariant uiVariant;
@property (nonatomic) BOOL enableMicrophone;
@property (nonatomic) BOOL enableSoundGuides;
@property (nonatomic) BOOL countdownEnabled;
- (nonnull instancetype)initWithUiVariant:(enum IDFlowVideoUiVariant)uiVariant enableMicrophone:(BOOL)enableMicrophone enableSoundGuides:(BOOL)enableSoundGuides countdownEnabled:(BOOL)countdownEnabled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, IDFlowVideoUiVariant, open) {
  IDFlowVideoUiVariantVariant1 = 0,
  IDFlowVideoUiVariantVariant2 = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
